### ISSUE TITLE
Can not install v0.0.48 or higher 

### ISSUE THREAD

**Issue by ilbonte** [ivoputzer/m.test#38]
Node: v7.4.0
Npm: v4.0.5
OS: macOS sierra

Version 0.0.47 works

![image](https://cloud.githubusercontent.com/assets/7412876/22755745/c211d5fe-ee44-11e6-95d4-762ddfb84948.png)

This is the error

`npm ERR! addLocal Could not install /Users/XPeppers/Desktop/JS/string-calculator-kata/node_modules/m.test/lib/watch
npm ERR! addLocal Could not install /Users/XPeppers/Desktop/JS/string-calculator-kata/node_modules/m.test/lib/no-ansi
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "install" "-D" "m.test@0.0.48"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! path /Users/XPeppers/Desktop/JS/string-calculator-kata/node_modules/m.test/lib/watch
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/XPeppers/Desktop/JS/string-calculator-kata/node_modules/m.test/lib/watch'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/XPeppers/Desktop/JS/string-calculator-kata/node_modules/m.test/lib/watch'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:`

[npm-debug.log](https://github.com/ivoputzer/m.test/files/761862/npm-debug.txt)

**Comment by ivoputzer** [comment]
looks like something went wrong on the ci, i will give it a look!

thanks for reporting! @ilbonte

**Comment by christian-fei** [comment]
Could it be because of a a syntax error in the binary?

https://travis-ci.org/ivoputzer/m.test/jobs/199751523#L442-L444

**Comment by ivoputzer** [comment]
yeah. it looks like `xargs -o` is available on BSD only!

-o    Reopen stdin as /dev/tty in the child process 
        before executing the command.  This is useful 
        if you want xargs to run an interactive application.

i guess the time has come to migrate those binaries to nodejs scripts themselves ;)

**Comment by christian-fei** [comment]
yeah ;)

**Comment by ivoputzer** [comment]
`xargs sh -c '</dev/tty node "$@"'` might be a quick-fix or gnu's `parallel` command.

**Comment by ivoputzer** [comment]
v0.0.48 has been deprecated! thanks y'all!
