### ISSUE TITLE
integration with travis doesn't work

### ISSUE THREAD

**Issue by AlessioCoser** [ivoputzer/m.test#40]
## expected behavior
I expected that m.test returns 1 if there is a failing test

## steps to reproduce
1.Write a failing test
2. push
3.see the Travis ci passing (It should fail)

## specification
- m.test version: 0.0.53
- node version: 7

**Comment by ivoputzer** [comment]
`m.test` uses travis itself and **unfortunately** we do have red builds due to broken tests. could you please provide the affected `.travis.yml` along with the test suite to reproduce this issue? does this issue appear only travis or does your suite zero-exit locally as well?

**Comment by ivoputzer** [comment]
#4a8ae66 should actually fix the issue! i will deprecate `v0.0.53` once `v0.0.54` is out! thanks for spotting this issue 👍 @AlessioCoser 

i encourage users to use [m.noansi](https://www.npmjs.com/package/m.noansi) instead of `--no-ansi` to strip ansi escape codes for now ;)
