### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by XhmikosR** [ivoputzer/m.test#42]
Hi, @ivoputzer.

So, it seems m.test requires bash. Can you replace bin/m.test with a node.js, cross-platform script?

PS. for Windows CI testing you can try AppVeyor (not affiliated with them)

**Comment by ivoputzer** [comment]
thanks for pointing this out @XhmikosR. making the binary cross-platform implies a bit of work though i will look forward to get this done as soon as possible since it was in the making anyway ;)
